#!/bin/bash
\cp -f .vimrc ~/.vimrc
\cp -f .vimrc.gui /Applications/MacVim.app/Contents/Resources/vim/
\cp -f .gvimrc /Applications/MacVim.app/Contents/Resources/vim/
\cp -f .zshrc ~/
\cp -f .tmux.conf ~/

